# nom de l'action
name: laravel-tests
on:
  # je specifie quand je dois lancer l'action, ici quand je push ou pull request sur la branche principale
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # nom du job
  laravel-tests:
# on choisis la VM sur laquel elle doit tournez
    runs-on: ubuntu-latest
# liste des etapes
    steps:
      # on installe php avec la version trouvez avec {{phpversion()}}
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4.7'
          # la machine recupere notre repot
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        # j'installe les dependances
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Migrate
        run: php artisan migrate
        # je créé une nouvelle clé
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
